version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    healthcheck:
       test: ["CMD", "curl", "-f", "http://localhost:6379/1"]
       interval: 30s
       timeout: 10s
       retries: 3
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    depends_on:
      - redis
    links:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/1
  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    depends_on:
      - redis
      - server
    links:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/1
