# Dockerfile to run the client within Alpine
# RT ~ 2018/07/30

FROM alpine:3.8
LABEL maintainer "Raphael Theberge"

RUN apk add --no-cache python3 python3-dev

ADD src /srv/Friendly-hello-world/src
COPY dockerconfigs/client/start.sh /

RUN python3 -m venv /srv/Friendly-hello-world/_venv && \
    . /srv/Friendly-hello-world/_venv/bin/activate && \
    pip install -r /srv/Friendly-hello-world/src/requirements.txt

ENV PYTHONUNBUFFERED=true

USER nobody
CMD /start.sh
